# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

os:
  - linux
  - osx

r:
  - 3.5.0
sudo: false
cache: packages
repos:
  CRAN: https://cloud.r-project.org
